---
title: "graphsforprojectcont"
author: "Gayane Hovsepyan"
date: "March 13, 2017"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$CTotal ~ mydata$Father_birth_age, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$CTotal ~ mydata$Father_birth_age, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
#options(show.signif.stars=F) #turning off significance stars
#anova(lm.out) #gives ANOVA table
plot(mydata$CTotal~ mydata$Father_birth_age, mydata='output3.csv', xlab = "Age of Father", ylab= "ADOS Total C", main="Age of Father at Birth vs ADOS Total C") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$Dtotal ~ mydata$Father_birth_age, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$Dtotal ~ mydata$Father_birth_age, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$Dtotal~ mydata$Father_birth_age, mydata='output3.csv', xlab = "Age of Father", ylab= "ADOS Total D", main="Age of Father vs ADOS Total D") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$Dtotal ~ mydata$Mother_birth_age, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$Dtotal ~ mydata$Mother_birth_age, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$Dtotal~ mydata$Mother_birth_age, mydata='output3.csv', xlab = "Age of Mother", ylab= "ADOS Total D", main="Age of Mother vs ADOS Total D") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$CTotal ~ mydata$Mother_birth_age, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$CTotal ~ mydata$Mother_birth_age, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc 
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$CTotal~ mydata$Mother_birth_age, mydata='output3.csv', xlab = "Age of Father", ylab= "ADOS Total C", main="Age of Mother vs ADOS Total C") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$Diagnosis_age ~ mydata$BTotal, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$Diagnosis_age ~ mydata$BTotal, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=T) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$Diagnosis_age ~ mydata$BTotal, mydata='output3.csv', xlab = "ADOS Total B", ylab= "Age of Diagnosis", main="ADOS Total B vs. Age of Diagnosis") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$Diagnosis_age ~ mydata$ATotal, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$Diagnosis_age ~ mydata$ATotal, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$Diagnosis_age ~ mydata$ATotal, mydata='output3.csv', xlab = "ADOS Total A", ylab= "Age of Diagnosis", main="ADOS Total A vs. Age of Diagnosis") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$Diagnosis_age ~ mydata$CTotal, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$Diagnosis_age ~ mydata$CTotal, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$Diagnosis_age ~ mydata$CTotal, mydata='output3.csv', xlab = "ADOS Total B", ylab= "Age of Diagnosis", main="ADOS Total C vs. Age of Diagnosis") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$Diagnosis_age ~ mydata$Dtotal, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$Diagnosis_age ~ mydata$Dtotal, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$Diagnosis_age ~ mydata$Dtotal, mydata='output3.csv', xlab = "ADOS Total B", ylab= "Age of Diagnosis", main="ADOS Total D vs. Age of Diagnosis") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$BTotal ~ mydata$Father_birth_age, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$BTotal ~ mydata$Father_birth_age, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc 
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$BTotal~ mydata$Father_birth_age, mydata='output3.csv', xlab = "Age of Father", ylab= "ADOS Total B", main="Age of Father vs ADOS Total B") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$BTotal ~ mydata$Father_birth_age, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$BTotal ~ mydata$Father_birth_age, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$BTotal~ mydata$Father_birth_age, mydata='output3.csv', xlab = "Age of Father", ylab= "ADOS Total B", main="Age of Father vs ADOS Total B") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red

```
## Histogram of Female vs Male Ados Scores
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist((newdata$ATotal)[newdata$Gender == 1], freq = FALSE, col=rgb(1,0,0,0.5), ylim = c(0,0.3), main="Gender and ADOS A total", xlab="ADOS A Total") #male ados scores
hist(newdata$ATotal[newdata$Gender == 2], freq = FALSE, col=rgb(0,0,1,0.5), add=T)
box() #female ados scores
legend(x = "topright", # location of legend within plot area
 c("Male", "Female"), #labels
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)), #colors
 lwd = c(10, 10))
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist((newdata$BTotal)[newdata$Gender == 1], freq = FALSE, col=rgb(1,0,0,0.5), ylim = c(0,0.3), breaks = 20, main="Gender and ADOS B total", xlab="ADOS B Total")
hist(newdata$BTotal[newdata$Gender == 2], freq = FALSE, breaks = 15, col=rgb(0,0,1,0.5), add=T)
box()
legend(x = "topright", # location of legend within plot area
 c("Male", "Female"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist((newdata$CTotal)[newdata$Gender == 1], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 20, ylim = c(0,0.50), main="Gender and ADOS C total", xlab="ADOS C Total")
hist(newdata$CTotal[newdata$Gender == 2], breaks = 10, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
box()
legend(x = "topright", # location of legend within plot area
 c("Male", "Female"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
```
```{r}
hist(newdata$Father_birth_age[newdata$ATotal >= 5], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 25, ylim = c(0,0.25), main=" Father's Age and ADOS A Totals", xlab="Father's age during birth of child")
hist(newdata$Father_birth_age[newdata$ATotal < 5], breaks = 30, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
box()
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
```
```{r}
# Pink is clinical, purple is subclinical
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist(newdata$Father_birth_age[newdata$BTotal >= 9], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 30, ylim = c(0,0.25), main=" Father's Age and ADOS B totals", xlab="Father's age during birth of child")
hist(newdata$Father_birth_age[newdata$BTotal < 9], breaks = 30, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
box()
```
```{r}
# Pink is clinical, purple is subclinical
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist(newdata$Father_birth_age[newdata$CTotal >= 3], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 40, ylim = c(0,0.25), main=" Father's Age and ADOS C totals", xlab="Father's age during birth of child")
hist(newdata$Father_birth_age[newdata$CTotal < 3], breaks = 40, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
box()
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
```
```{r}
# Pink is clinical, purple is subclinical
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist(newdata$Father_birth_age[newdata$Dtotal >= 3], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 35, ylim = c(0,0.25), main=" Father's Age and ADOS D totals", xlab="Father's age during birth of child")
hist(newdata$Father_birth_age[newdata$Dtotal < 3], breaks = 47, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
box()
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist((newdata$Dtotal)[newdata$Gender == 1], freq = FALSE, breaks = 8, col=rgb(1,0,0,0.5), ylim = c(0,0.6), main="Gender and ADOS D total", xlab="ADOS D Total")
hist(newdata$Dtotal[newdata$Gender == 2], freq = FALSE, breaks = 10, col=rgb(0,0,1,0.5), add=T)
box()
legend(x = "topright", # location of legend within plot area
 c("Male", "Female"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist((newdata$Diagnosis_age)[newdata$Gender == 1], freq = FALSE, breaks = 30, col=rgb(1,0,0,0.5), ylim = c(0,1.3), main="Gender and Age of Diagnosis", xlab="Age of Diagnosis")
hist(newdata$Diagnosis_age[newdata$Gender == 2], freq = FALSE, breaks = 30, col=rgb(0,0,1,0.5), add=T)
legend(x = "topright", # location of legend within plot area
 c("Male", "Female"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
box()
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist(newdata$Mother_birth_age[newdata$ATotal >= 5], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 35, ylim = c(0,0.20), main=" Mother's Age and ADOS A totals", xlab="Mother's age during birth of child")
hist(newdata$Mother_birth_age[newdata$ATotal < 5], breaks = 25, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
box()
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist(newdata$Mother_birth_age[newdata$BTotal >= 9], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 30, ylim = c(0,0.20), main="Mother's Age and ADOS B totals", xlab="Mother's age during birth of child")
hist(newdata$Mother_birth_age[newdata$BTotal < 9], breaks = 20, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
box()
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist(newdata$Mother_birth_age[newdata$CTotal >= 3], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 35, ylim = c(0,0.25), main="Mother's Age and ADOS C totals", xlab="Mother's age during birth of child")
hist(newdata$Mother_birth_age[newdata$CTotal < 3], breaks = 25, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
box()
```
```{r}
newdata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
hist(newdata$Mother_birth_age[newdata$Dtotal >= 3], freq = FALSE, col=rgb(1,0,0,0.5), breaks = 20, ylim = c(0,0.25), main=" Mother's Age and ADOS D totals", xlab="Mother's age during birth of child")
hist(newdata$Mother_birth_age[newdata$Dtotal < 3], breaks = 30, freq = FALSE, col=rgb(0,0,1,0.5), add=T)
legend(x = "topright", # location of legend within plot area
 c("Greater than or equal to median score", "Less than median score"),
 col = c(rgb(1,0,0,0.5),rgb(0,0,1,0.5)),
 lwd = c(10, 10))
box()
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
getwd()
mydata <- read.csv("/home/eeb177-student/Desktop/eeb-177-final-project/output3.csv", na.strings = "NULL")
lm (mydata$Diagnosis_age ~ mydata$MHLE, mydata = 'output3.csv') #linear regression of Age of father field vs ADOS total A field)
lm.out = lm (mydata$Diagnosis_age ~ mydata$MHLE, mydata= "output3.csv", na.strings="NULL") #naming output
summary(lm.out) #gives LOTS of info about output, including coefficients, R values, R^2 etc
options(show.signif.stars=F) #turning off significance stars
anova(lm.out) #gives ANOVA table
plot(mydata$Diagnosis_age ~ mydata$MHLE, xlim = c(2,10), mydata='output3.csv', xlab= "MHLE", ylab = "Age of Diagnosis", main="MHLE vs. Age of Diagnosis") #plotting linear regression and naming plot
abline(lm.out, col="red") #linear regression line red
```

